version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: panthon
      MYSQL_DATABASE: todos
    volumes:
      - todo-mysql-data:/var/lib/mysql:rw

  todo-app:
    image: panthonk/panthon-todo4
    ports:
      - 3300:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: panthon
      MYSQL_DB: todos

volumes:
  todo-mysql-data: